### ISSUE TITLE
Upgrade python version on the nodes

### ISSUE THREAD

**Issue by PolinaKiporenko** [skalenetwork/node-provisioning#61]
Python 3.6 is not supported since 21 Dec 2021. We need to make sure that all nodes are operating available.
We need to add corresponding tasks in node provision as well as clear instruction how to upgrade python version on validators machine.

**Comment by badrogger** [comment]
Moving to node-cli repo

**Comment by EvgeniyZZ** [comment]
Not require QA afford

**Comment by DmytroNazarenko** [comment]
Moved to incomplete per @badrogger request
